### ISSUE TITLE
Userstory: Selection for HTTP method type

### ISSUE THREAD

**Issue by nstrelow** [HPI-SWA-Teaching/SWT16-Project-03#2]
A webdeveloper wants to select a HTTP method type (GET, POST, UPDATE, DELETE) from a dropdown selection field so he can send different requests. (Set header differently)

**Comment by AlecSchneider** [comment]
workin on post requests

**Comment by m0r13** [comment]
Füg mal noch update und delete der vollständigkeit halber einfach zum dropdown hinzu.
